# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Fuel consumption of Trucks Challenge
short_description: A private challenge for predicting fuel consumption of trucks
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard for the challenge.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2021-12-09 00:00:00
end_date: 2022-01-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["MAE", "RMSE"],
        "default_order_by": "MAE",
        "metadata": {
          "MAE": {
            "sort_ascending": True,
            "description": "Mean Absolute Error.",
          },
          "RMSE": {
            "sort_ascending": True,
            "description": "Root Mean Squared Error.",
          }
        }
      }


challenge_phases:
  - id: 1
    name: Public Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-12-09 00:00:00
    end_date: 2022-01-31 23:59:59
    test_annotation_file: annotations/private_solution.csv
    codename: public
    max_submissions_per_day: 20
    max_submissions_per_month: 500
    max_submissions: 500
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".csv"

dataset_splits:
  - id: 1
    name: Public Split
    codename: public_split
  - id: 2
    name: Private Split
    codename: private_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
